version = 1
enabled = true

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]
  module_system = "es-modules"
  dialect = "typescript"

[[transformers]]
name = "prettier"